server:
  port: 80

logging:
  level:
    org.springframework: DEBUG

spring:
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  messages:
#    basename: messages
#  security:
#    user:
#      name: username
#      password: passw0rd

# ??
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
